#Docker compose we can create sevices
#The services are the container that we want to run
services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: demo_docker
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spring-boot-network
  spring-boot-app:
    container_name: spring-demo
    image: spring/demo
    ports:
      - "8088:8080"
    networks:
      - spring-boot-network
    # we need to make sure that our database it is up and running we nne to make image spring wait the postgres
    depends_on:
      - postgres

volumes:
  #this postgres will refer to "postgres:" in line 13
  postgres:

networks:
  spring-boot-network:
    driver: bridge